/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;
import java.util.Map;
import java.util.Map.Entry;
import java.util.HashMap;

class MultiSet<T> {
    
    private Map<T, Integer> map;

    public MultiSet() {
        this.map = new HashMap<T, Integer>();
    }
 
    void add(T t) {
        if(map.containsKey(t)) {
            map.put(t, map.get(t) + 1);
        } else {
            map.put(t, 1);
        }
    }

    public void addAll(MultiSet<T> set) {
        set.map.entrySet().forEach((Entry<T, Integer> entry) ->  {
            T t = entry.getKey();
            Integer v = entry.getValue();
            if(map.containsKey(t) ){
                map.put(t, map.get(t) + v);
            } else {
                map.put(t, v);
            }
        });
    }
 
    public void remove(T t) {
        Integer read = map.get(t);
        if(read == null) {
            return;
        } else if(read > 1) {
            map.put(t, read - 1);
        } else if(read == 1) {
            map.remove(t);
        }
    }

    public boolean contains(T element) {
        return this.map.containsKey(element);
    }
 
    public static void main(String[] args) {
        MultiSet<String> set = new MultiSet<>();
        set.add("test");
        set.add("test");
        set.add("test");
         
        set.remove("test");
        System.out.println(set.contains("test")); // true
         
        set.remove("test");
        System.out.println(set.contains("test")); // true
         
        set.remove("test");
        System.out.println(set.contains("test")); // true
    }
}
